const data = [
  {
    name: "Radisson Blu Hotel",
    location: "Paschim Vihar",
    star: 5,
    rating: 4.6,
    price: 6328,
    category: "hotel",
    image: "radisson-blu-hotel.jpg",
  },
  {
    name: "Seven Seas Hotel",
    location: "Rohini",
    star: 5,
    rating: 4.3,
    price: 5247,
    category: "hotel",
    image: "seven-seas-hotel.jpg",
  },
  {
    name: "Jaypee Siddarth",
    location: "Rajendra Place",
    star: 4,
    rating: 4.2,
    price: 5655,
    category: "hotel",
    image: "jaypee-siddharth.jpg",
  },
  {
    name: "Roseate House",
    location: "Aerocity",
    star: 5,
    rating: 4.5,
    price: 9439,
    category: "hotel",
    image: "roseate-house.jpg",
  },
  {
    name: "Hotel Waterfall",
    location: "Paschim Vihar",
    star: 3,
    rating: 3.9,
    price: 2180,
    category: "hotel",
    image: "hotel-waterfall.jpg",
  },
  {
    name: "Hotel Picasso",
    location: "Paschim Vihar",
    star: 3,
    rating: 3.7,
    price: 2520,
    category: "hotel",
    image: "hotel-picasso.jpg",
  },

  {
    name: "Select Citywalk",
    location: "Pushp Vihar",
    rating: 4.3,
    openingTime: 9,
    closingTime: 10,
    category: "mall",
    image: "select-citywalk.jpg",
  },
  {
    name: "DLF Promenade Mall",
    location: "R.K. Puram",
    rating: 4.1,
    openingTime: 11,
    closingTime: 10,
    category: "mall",
    image: "dlf-promenade.jpg",
  },
  {
    name: "AeroCity Central",
    location: "Aerocity",
    rating: 3.8,
    openingTime: 12,
    closingTime: 9,
    category: "mall",
    image: "aerocity-central.jpg",
  },
  {
    name: "City Center Mall",
    location: "Rohini",
    rating: 3.9,
    openingTime: 11,
    closingTime: 11,
    category: "mall",
    image: "city-center-mall.jpg",
  },
  {
    name: "Square One Mall",
    location: "Pushp Vihar",
    rating: 4.1,
    openingTime: 11,
    closingTime: 9,
    category: "mall",
    image: "square-one-mall.jpg",
  },
  {
    name: "Unity One Mall",
    location: "Rohini",
    rating: 3.5,
    openingTime: 9,
    closingTime: 10,
    category: "mall",
    image: "unity-one-mall.jpg",
  },
  {
    name: "Southern Park Mall",
    location: "Saket",
    rating: 4.1,
    openingTime: 11,
    closingTime: 9,
    category: "mall",
    image: "southern-park-mall.jpg",
  },
  {
    name: "Geetanjali Salon",
    location: "Saket",
    rating: 4.4,
    openingTime: 9,
    closingTime: 9,
    years: 5,
    category: "salon",
    image: "geetanjali-salon.png",
  },
  {
    name: "Asin Salon",
    location: "R.K. Puram",
    rating: 3.9,
    openingTime: 9,
    closingTime: 9,
    years: 3,
    category: "salon",
    image: "asin-salon.jpg",
  },
  {
    name: "SANRIX Salon",
    location: "Paschim Vihar",
    rating: 4.7,
    openingTime: 10,
    closingTime: 9,
    years: 5,
    category: "salon",
    image: "sanrix-salon.jpeg",
  },
  {
    name: "Elvis & Reema Salon",
    location: "Greater Kailash",
    rating: 4.6,
    openingTime: 10,
    closingTime: 8,
    years: 7,
    category: "salon",
    image: "elvis-reema-salon.jpg",
  },
  {
    name: "Looks Salon",
    location: "Aerocity",
    rating: 4,
    openingTime: 10,
    closingTime: 7,
    years: 3,
    category: "salon",
    image: "looks-salon.jpg",
  },

  {
    name: "Max Super Speciality Hospital",
    location: "Saket",
    rating: 3.8,
    founded: 2006,
    category: "hospital",
    image: "max-super-speciality.jpg",
  },
  {
    name: "Apollo Children's Hospital",
    location: "Greater Kailash",
    rating: 4.8,
    founded: 2010,
    category: "hospital",
    image: "apollo-children-hospital.jpg",
  },
  {
    name: "Indraprastha Apollo Hospital",
    location: "Pushp Vihar",
    rating: 4.8,
    founded: 1995,
    category: "hospital",
    image: "indraprastha-apollo.jpg",
  },
  {
    name: "Sir Ganga Ram Hospital",
    location: "Rajendra Place",
    rating: 3.6,
    founded: 1954,
    category: "hospital",
    image: "sir-ganga-ram.jpg",
  },
  {
    name: "Modern School",
    location: "Greater Kailash",
    rating: 3.8,
    principal: "Dr Vijay Datta",
    founded: 1920,
    faculty: 120,
    category: "school",
    image: "modern-school.jpg",
  },
  {
    name: "Manav Sthali School",
    location: "Rajendra Place",
    rating: 3.75,
    principal: "Mrs. Dipti bhatnagar",
    founded: 1957,
    faculty: 150,
    category: "school",
    image: "manav-sthali-school.jpg",
  },
  {
    name: "Delhi Public School R.K.Puram",
    location: "R.K. Puram",
    rating: 4.3,
    principal: "Ms. Padma Srinivasan",
    founded: 1972,
    faculty: 221,
    category: "school",
    image: "dps-rk-puram.jpg",
  },
];
